### ISSUE TITLE
hungarianMatch is undefined

### ISSUE THREAD

**Issue by rkruegs123** [faskowit/blockmodelTools#1]
Where can I find the `hungarianMatch` function?

**Comment by faskowit** [comment]
You'll need two functions added to your path: 

hungarianMatch (either rename... or change the code to this function name) -> 
https://github.com/ThomasYeoLab/CBIG/blob/master/utilities/matlab/parcellation/CBIG_HungarianClusterMatch.m

Which uses the munkres function -> 
https://www.mathworks.com/matlabcentral/fileexchange/20652-hungarian-algorithm-for-linear-assignment-problems-v2-3

**Comment by rkruegs123** [comment]
Thank you!
